version: "3.8"

services:
  app:
    image: docker-all-the-way/app-run-local:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./src/:/opt/src/"
      - "./tests/:/opt/tests/"
    environment:
      DEBUG: 0
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - "./nginx/templates/:/etc/nginx/templates/"
      - "./nginx/certs:/etc/nginx/certs/"
    environment:
      - NGINX_SERVER_NAME=localhost
      - NGINX_HTTPS_REDIRECT_PORT=4433
      - NGINX_SSL_CERTIFICATE=localhost+2.pem
      - NGINX_SSL_CERTIFICATE_KEY=localhost+2-key.pem
