version: "3.8"

services:
  app:
    image: docker-all-the-way/app-run-local:latest
    container_name: docker-all-the-way-app
    environment:
      DEBUG: 0
    secrets:
      - postgres_password
      - postgres_user
    depends_on:
      - db
  nginx:
    image: nginx:1.21-alpine
    container_name: docker-all-the-way-nginx
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - "./nginx/templates/:/etc/nginx/templates/"
      - "./nginx/certs:/etc/nginx/certs/"
    environment:
      - NGINX_SERVER_NAME=localhost
      - NGINX_HTTPS_REDIRECT_PORT=4433
      - NGINX_SSL_CERTIFICATE=localhost+2.pem
      - NGINX_SSL_CERTIFICATE_KEY=localhost+2-key.pem
    depends_on:
      - app
  db:
    image: postgres:14.2
    container_name: docker-all-the-way-db
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
