version: "3.8"

services:
  app:
    image: docker-all-the-way/app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./src/:/opt/src/"
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
